name: PVPToggle
version: '1.2.0'
main: com.lukeonuke.pvptoggle.PvpToggle
api-version: '1.20'
commands:
  pvp:
    description: "Allow players to toggle PVP individually."
    usage: /<command>
    permission: pvptoggle.pvp
permissions :
  pvptoggle.pvp.others:
    description: "Allows the player to toggle PVP for other players."
    default: op
  pvptoggle.pvp:
    description: "Allows the player to toggle their own PVP."
    default: true
  pvptoggle.reload:
    description: "Reload the plugin."
    default: op